source "https://rubygems.org"

gem 'sinatra'
gem 'activerecord', '5.2', :require => 'active_record'
gem 'sinatra-activerecord', :require => 'sinatra/activerecord'
gem 'rake'
gem 'require_all' 
gem 'sqlite3', '~> 1.3.7'
gem 'thin'
gem 'shotgun'
gem 'pry'
gem 'bcrypt'
gem 'tux', '~> 0.3.0'
gem 'rack-flash3'
gem 'sinatra-flash'
